# Generated by Django 5.0.2 on 2026-01-19 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("url", models.URLField(max_length=500)),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "ttfb",
                    models.FloatField(
                        blank=True, help_text="Time to First Byte (ms)", null=True
                    ),
                ),
                (
                    "lcp",
                    models.FloatField(
                        blank=True, help_text="Largest Contentful Paint (ms)", null=True
                    ),
                ),
                (
                    "cls",
                    models.FloatField(
                        blank=True, help_text="Cumulative Layout Shift", null=True
                    ),
                ),
                (
                    "inp",
                    models.FloatField(
                        blank=True,
                        help_text="Interaction to Next Paint (ms)",
                        null=True,
                    ),
                ),
                (
                    "fcp",
                    models.FloatField(
                        blank=True, help_text="First Contentful Paint (ms)", null=True
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "network_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "scroll_depth",
                    models.FloatField(default=0, help_text="Percentage scrolled"),
                ),
                (
                    "time_on_page",
                    models.FloatField(default=0, help_text="Seconds spent on page"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Visit",
                "verbose_name_plural": "Page Visits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ErrorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("status_code", models.PositiveIntegerField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.pagevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Event",
                "verbose_name_plural": "Error Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("rage_click", "Rage Click"),
                            ("click", "Click"),
                            ("form_submit", "Form Submit"),
                            ("cart_add", "Add to Cart"),
                            ("checkout", "Checkout"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "element_selector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="analytics.pagevisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Interaction",
                "verbose_name_plural": "User Interactions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
