# Generated by Django 5.0.2 on 2026-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analytics",
            "0002_pagevisit_city_pagevisit_country_pagevisit_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="isp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
