"""
Django settings for _main project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import re
import secrets
from pathlib import Path


import dj_database_url
import semver
from celery.schedules import crontab

from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ImproperlyConfigured
import environ
from _main.secret_utils import require_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, ".env"), override=False)

# Log the loaded Redis/Valkey URL for debugging
redis_url = os.environ.get('REDIS_URL', 'Not Set')
if os.environ.get("RUN_MAIN"):
    print(f"Loading settings with REDIS_URL: {redis_url}")

# Before using your app in production, make sure to review Django's deployment checklist:
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Django requires a unique secret key for each Django app, that is used by several of its
# security features. To simplify initial setup (without hardcoding the secret in the source
# code) we set this to a random value every time the app starts. However, this will mean many
# Django features break whenever an app restarts (for example, sessions will be logged out).
# In your production apps you should set the `DJANGO_SECRET_KEY` config var explicitly.
# Make sure to use a long unique value, like you would for a password. See:
# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-SECRET_KEY
# SECURITY WARNING: keep the secret key used in production secret!

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

SECRET_KEY = env('SECRET_KEY')

IS_FLY_APP = env.str("FLY_APP", default="")
IS_PRODUCTION = bool(IS_FLY_APP) or env.str("ENVIRONMENT", default="") == "production"

DEFAULT_HUB_BASE_URL = "https://hub.krispc.fr" if IS_PRODUCTION else "http://hub.localhost:8000"
DEFAULT_KRISPC_BASE_URL = "https://com.krispc.fr" if IS_PRODUCTION else "http://com.localhost:8000"
DEFAULT_P2C_BASE_URL = "https://p2c.krispc.fr" if IS_PRODUCTION else "http://p2c.localhost:8000"
DEFAULT_PLEXUS_BASE_URL = "https://plexus.krispc.fr" if IS_PRODUCTION else "http://plexus.localhost:8000"
DEFAULT_EMO_BASE_URL = "https://emo.krispc.fr" if IS_PRODUCTION else "http://emo.localhost:8000"
DEFAULT_SAS_BASE_URL = "https://sas.krispc.fr" if IS_PRODUCTION else "http://sas.localhost:8000"

HUB_BASE_URL = env("HUB_BASE_URL", default=DEFAULT_HUB_BASE_URL).rstrip("/")
KRISPC_BASE_URL = env("KRISPC_BASE_URL", default=DEFAULT_KRISPC_BASE_URL).rstrip("/")
P2C_BASE_URL = env("P2C_BASE_URL", default=DEFAULT_P2C_BASE_URL).rstrip("/")
PLEXUS_BASE_URL = env("PLEXUS_BASE_URL", default=DEFAULT_PLEXUS_BASE_URL).rstrip("/")
EMO_BASE_URL = env("EMO_BASE_URL", default=DEFAULT_EMO_BASE_URL).rstrip("/")
SAS_BASE_URL = env("SAS_BASE_URL", default=DEFAULT_SAS_BASE_URL).rstrip("/")

CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[
    "https://krispc.fr",
    "https://www.krispc.fr",
    "https://hub.krispc.fr",
    "https://com.krispc.fr",
    "https://p2c.krispc.fr",
    "https://plexus.krispc.fr",
    "https://emo.krispc.fr",
    "https://sas.krispc.fr",
    "https://pdf2cal.fly.dev",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://plexus.localhost:8000",
    "http://hub.localhost:8000",
    "http://www.localhost:8000",
    "http://sas.localhost:8000",
])

MAPBOX_TOKEN = env('MAPBOX_TOKEN')
MAPBOX_ACCESS_TOKEN = env("MAPBOX_ACCESS_TOKEN", default=MAPBOX_TOKEN)
MAPBOX_DOWNLOADS_TOKEN = env("MAPBOX_DOWNLOADS_TOKEN", default=None)



DEBUG = False
# SECURITY WARNING: don't run with debug turned on in production!
if not IS_PRODUCTION:
    DEBUG = True

EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "false").lower() in ("1", "true", "yes")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() in ("1", "true", "yes")

# On fly.io, it's safe to use a wildcard for `ALLOWED_HOSTS`, since the proxy performs
# validation of the Host header in the incoming HTTP request. On other platforms you may need
# to list the expected hostnames explicitly to prevent HTTP Host header attacks. See:
# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-ALLOWED_HOSTS
if IS_PRODUCTION:
    ALLOWED_HOSTS = ["*"]
    
    # Security Settings for Production
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Redirect non-www to www
    PREPEND_WWW = False
else:
    ALLOWED_HOSTS = []

# CORS Configuration for API
# Allow API access from specific origins
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "https://krispc.fr",
    "https://www.krispc.fr",
    "https://hub.krispc.fr",
    "https://com.krispc.fr",
    "https://p2c.krispc.fr",
    "https://plexus.krispc.fr",
    "https://emo.krispc.fr",
    "https://sas.krispc.fr",
    "http://localhost:3000",
    "http://localhost:5173",
])

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'accept-language',
]



# Application definition

INSTALLED_APPS = [
    "daphne",
    # Use WhiteNoise's runserver implementation instead of the Django default, for dev-prod parity.
    "whitenoise.runserver_nostatic",
    # Uncomment this and the entry in `urls.py` if you wish to use the Django admin feature:
    # https://docs.djangoproject.com/en/4.2/ref/contrib/admin/
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Vite integration for modern frontend
    "django_vite",
    # "django_user_agents",
    "django_htmx",
    "channels",
    
    # Core Apps
    "krispc",
    "p2c",
    "celery_progress",
    "hub",
    "analytics",
    "plexus.apps.PlexusConfig",
    "emoty",
    "sas",

    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "django_filters",
    "corsheaders",

    # Stream management (MediaMTX integration)
    "streams",
]

try:
    import turnstile  # noqa: F401
except Exception:
    pass
else:
    INSTALLED_APPS.append("turnstile")

ASGI_APPLICATION = '_main.asgi.application'
WSGI_APPLICATION = '_main.wsgi.application'

# Django Vite configuration for modern frontend assets
DJANGO_VITE = {
    'default': {
        'dev_mode': False,  # Set to False to use production build
        'dev_server_host': 'localhost',
        'dev_server_port': 5173,
        'manifest_path': BASE_DIR / 'krispc' / 'static' / 'dist' / '.vite' / 'manifest.json',
        'app_client_class': 'krispc.vite.ReloadingDjangoViteAppClient',
    }
}

REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')

# MediaMTX stream server (Fly private networking)
MEDIAMTX_URL = os.environ.get('MEDIAMTX_URL', 'http://mediamtx-krispc.internal:9997')
# TTL in seconds for the Valkey stream-status cache
MEDIAMTX_STREAM_CACHE_TTL = int(os.environ.get('MEDIAMTX_STREAM_CACHE_TTL', '10'))

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "hello@krispc.fr")
SAS_ACCESS_EMAIL = os.environ.get("SAS_ACCESS_EMAIL", "archer.chris@gmail.com")
SAS_IPINFO_TOKEN = require_secret(
    "SAS_IPINFO_TOKEN",
    is_production=IS_PRODUCTION,
    dev_default="",
)
SAS_IPINFO_TIMEOUT_SECONDS = int(os.environ.get("SAS_IPINFO_TIMEOUT_SECONDS", "2"))
SAS_TURNSTILE_EXPECTED_ACTION = os.environ.get("SAS_TURNSTILE_EXPECTED_ACTION", "sas_download")
SAS_TURNSTILE_EXPECTED_HOSTNAMES = env.list(
    "SAS_TURNSTILE_EXPECTED_HOSTNAMES",
    default=["sas.krispc.fr", "sas.localhost"],
)
SAS_TRUST_CF_CONNECTING_IP = os.environ.get("SAS_TRUST_CF_CONNECTING_IP", "false").lower() in (
    "1",
    "true",
    "yes",
)
SAS_TRUSTED_PROXY_IPS = env.list("SAS_TRUSTED_PROXY_IPS", default=[])
SAS_RATE_LIMIT_REQUESTS = int(os.environ.get("SAS_RATE_LIMIT_REQUESTS", "5"))
SAS_RATE_LIMIT_WINDOW_SECONDS = int(os.environ.get("SAS_RATE_LIMIT_WINDOW_SECONDS", "60"))
SAS_RATE_LIMIT_CACHE_ALIAS = os.environ.get("SAS_RATE_LIMIT_CACHE_ALIAS", "default")
TURNSTILE_SITEKEY = require_secret(
    "TURNSTILE_SITEKEY",
    is_production=IS_PRODUCTION,
    dev_default="1x00000000000000000000AA",
)
TURNSTILE_SECRET = require_secret(
    "TURNSTILE_SECRET",
    is_production=IS_PRODUCTION,
    dev_default="1x0000000000000000000000000000000AA",
)


if DEBUG:
    # Use in-memory channel layer for development
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    # Use Valkey/Redis for production (plain redis:// via Fly private networking)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Django doesn't support serving static assets in a production-ready way, so we use the
    # excellent WhiteNoise package to do so instead. The WhiteNoise middleware must be listed
    # after Django's `SecurityMiddleware` so that security redirects are still performed.
    # See: https://whitenoise.readthedocs.io
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "_main.subdomain_middleware.SubdomainRoutingMiddleware", # Subdomain Routing
    "hub.middleware.EnsureDefaultLanguageMiddleware",  # Restored
    "django.middleware.locale.LocaleMiddleware",  # Required for i18n URL patterns
    "krispc.middleware.APILanguageMiddleware",  # API-specific language detection
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "krispc.middleware.APIRequestLoggingMiddleware",  # API request logging
]

ROOT_URLCONF = "_main.urls"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "p2c" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.csrf",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "krispc.context_processors.hub_urls",
                "p2c.context_processors.unread_updates_context",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Uses SQLite by default. Can be overridden with DATABASE_URL environment variable.
# https://github.com/jazzband/dj-database-url

if IS_FLY_APP:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "/data/db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "fr"
# LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# Media files (uploaded by users)
if IS_FLY_APP:
    MEDIA_ROOT = Path("/data/media")
else:
    MEDIA_ROOT = BASE_DIR / "media"
    
MEDIA_URL = "/media/"

# Additional locations for static files
STATICFILES_DIRS = [
    BASE_DIR / "krispc" / "static" / "dist",  # Vite build output
    BASE_DIR / "krispc" / "static",           # Images and other static assets
    BASE_DIR / "p2c" / "static",              # P2C static files
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "krispc/locale"),
    os.path.join(BASE_DIR, "locale"),
]


LANGUAGES = [
    ("fr", _("French")),
    ("en", _("English")),
]

# Language cookie settings for session persistence
LANGUAGE_COOKIE_NAME = 'krispc_language'
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year
LANGUAGE_COOKIE_SAMESITE = 'Lax'
LANGUAGE_COOKIE_HTTPONLY = False  # Allow JS to read if needed

# Share session across subdomains
if IS_PRODUCTION:
    SESSION_COOKIE_DOMAIN = ".krispc.fr"
    CSRF_COOKIE_DOMAIN = ".krispc.fr"
else:
    # For localhost development with subdomains
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None

STORAGES = {
    # Default file storage for uploaded files
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Enable WhiteNoise's GZip and Brotli compression of static assets:
    # https://whitenoise.readthedocs.io/en/latest/django.html#add-compression-and-caching-support
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Don't store the original (un-hashed filename) version of static files, to reduce slug size:
# https://whitenoise.readthedocs.io/en/latest/django.html#WHITENOISE_KEEP_ONLY_HASHED_FILES
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

WHITENOISE_MANIFEST_STRICT = False

# Configure caching - Valkey/Redis-backed to support shared state (SAS rate limiting).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

VER = semver.VersionInfo.parse("2.3.0")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- P2C / PDF2Cal Specific Settings ---

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Connection timeout settings to prevent hanging when Redis is unavailable
CELERY_BROKER_CONNECTION_TIMEOUT = 10  # 10 seconds timeout for broker connection
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 3
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 10,
    'socket_connect_timeout': 10,
}

if DEBUG:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# No SSL needed — Valkey runs on Fly private networking (plain redis://)

# Celery Beat Schedule for periodic tasks
CELERY_BEAT_SCHEDULE = {
    'check-due-reminders': {
        'task': 'plexus.tasks.check_due_reminders',
        'schedule': 60.0,  # every 60 seconds
    },
    "sas-purge-old-access-logs": {
        "task": "sas.tasks.purge_old_access_logs",
        "schedule": crontab(minute=15, hour=3),
    },
    "sas-vacuum-sqlite-database": {
        "task": "sas.tasks.vacuum_sqlite_database",
        "schedule": crontab(minute=0, hour=4, day_of_week="sun"),
    },
    "refresh-stream-cache": {
        "task": "streams.tasks.refresh_stream_cache",
        "schedule": MEDIAMTX_STREAM_CACHE_TTL,  # keep cache warm
    },
}

# Google OAuth2 Settings
GOOGLE_OAUTH2_CLIENT_ID = env("GOOGLE_OAUTH2_CLIENT_ID", default=None)
GOOGLE_OAUTH2_CLIENT_SECRET = env("GOOGLE_OAUTH2_CLIENT_SECRET", default=None)
GOOGLE_OAUTH2_REDIRECT_URI = env("GOOGLE_OAUTH2_REDIRECT_URI", default="http://localhost:8000/google/callback")
GOOGLE_OAUTH2_SCOPES = [
    "openid",
    "email",
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/calendar.readonly",
]

REST_FRAMEWORK = {
    # Renderers
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # For development
    ],
    
    # Authentication
    # SessionAuthentication for browser flows (CSRF-protected).
    # TokenAuthentication for external API clients (Authorization: Token <key>).
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    
    # Permissions - Allow per-view control (views explicitly set their permissions)
    "DEFAULT_PERMISSION_CLASSES": [],
    
    # User settings
    "UNAUTHENTICATED_USER": None,
    
    # Schema generation
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    # Throttling
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "1000/hour",           # Anonymous users: 1000 requests per hour (increased for dev)
        "user": "5000/hour",          # Authenticated users: 5000 requests per hour
        "contacts": "50/minute",       # Contact form: 50 per minute
        "read_only": "600/minute",     # Read-only endpoints: 600 per minute
    },
    
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    
    # Filtering
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    
    # Versioning
    # AcceptHeaderVersioning engages with the existing /api/<app>/ URLs;
    # URLPathVersioning would require /api/v1/<app>/ which is a breaking
    # change for existing clients. Clients opt into version metadata via
    #   Accept: application/json; version=v1
    # New endpoints can branch on request.version when they need to.
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.AcceptHeaderVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    "VERSION_PARAM": "version",
    
    # Exception handling
    "EXCEPTION_HANDLER": "krispc.exceptions.custom_exception_handler",
    
    # Datetime format
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'KrisPC Suite API',
    'DESCRIPTION': (
        'Unified REST API for the KrisPC suite — KrisPC IT services, '
        'Pdf2Cal scheduling, Plexus SecondBrain, Emoty pattern engine, '
        'Streams (MediaMTX), and Analytics.\n\n'
        'Authentication: `SessionAuthentication` (browser/CSRF) or '
        '`TokenAuthentication` (external clients, header `Authorization: Token <key>`).\n\n'
        'Versioning: clients may pin via `Accept: application/json; version=v1`. '
        'The current and only published version is **v1**.\n\n'
        'Throttling: anonymous 1000/h, authenticated 5000/h. Scoped throttles '
        '(`contacts`, `read_only`) apply on specific endpoints.\n\n'
        'Errors: every error response follows the standard envelope '
        '`{"success": false, "message": ..., "errors": ...}`. Success envelopes '
        'follow `{"success": true, "data": ..., "message": ...}` when produced '
        'via `krispc.api_utils`.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {'name': 'KrisPC', 'email': 'hello@krispc.fr'},
    'LICENSE': {'name': 'Proprietary'},
    'TAGS': [
        {'name': 'KrisPC', 'description': 'IT services: contacts, products, brands, cities.'},
        {'name': 'Pdf2Cal', 'description': 'Schedule ingestion, calendar operations, beneficiaries.'},
        {'name': 'Plexus', 'description': 'SecondBrain capture, classification, action extraction.'},
        {'name': 'Emoty', 'description': 'Emoji pattern catalog and pricelist.'},
        {'name': 'Streams', 'description': 'MediaMTX live-stream management.'},
        {'name': 'Analytics', 'description': 'Visit tracking, dashboard data, performance metrics.'},
    ],
    'SERVERS': [
        {'url': 'https://com.krispc.fr', 'description': 'Production (KrisPC subdomain)'},
        {'url': 'http://localhost:8000', 'description': 'Local development'},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX_TRIM': True,
    'SORT_OPERATIONS': True,
}

# AI Configuration (Plexus)
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-pro-latest")

# Matches "Not Found: /<path>" entries from botnet vulnerability scans
# (PHP shells, .env leaks, .git exposure, framework probes, SQL dumps, etc.)
_SCAN_404_RE = re.compile(
    r"Not Found: /[^\s]*(?:"
    r"\.php"
    r"|\.env"
    r"|wp-"
    r"|\.git"
    r"|\.htpasswd|\.npmrc|\.netrc|\.gitconfig|\.dockerenv"
    r"|\.aws/|\.kube/|\.docker/|\.composer/"
    r"|actuator/"
    r"|\.sql"
    r"|secrets\.|credentials\."
    r"|appsettings|[Ww]eb\.config|Web\.[A-Z]"
    r"|swagger|openapi|api-docs"
    r"|terraform\.tf"
    r"|composer\.(?:json|lock)"
    r"|parameters\.yml|local\.settings\.json"
    r"|_profiler|server-(?:status|info)|nginx_status"
    r"|global\.asax|connectionstrings\.config|ecosystem\.config\.js"
    r"|\.runtimeconfig\.json|auth\.json"
    r"|%67%69%74|%65%6Ev|%77%70%2D"
    r")"
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "suppress_analytics_tracking": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: "/analytics/api/track/" not in record.getMessage(),
        },
        "suppress_404_scans": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: not _SCAN_404_RE.search(record.getMessage()),
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "console_filtered": {
            "class": "logging.StreamHandler",
            "filters": ["suppress_analytics_tracking"],
        },
        "console_no_scans": {
            "class": "logging.StreamHandler",
            "filters": ["suppress_404_scans"],
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "django.request": {"handlers": ["console_no_scans"], "level": "WARNING", "propagate": False},
        "p2c": {"handlers": ["console"], "level": "INFO", "propagate": True},
        "plexus": {"handlers": ["console"], "level": "INFO", "propagate": True},
        "daphne.server": {"handlers": ["console_filtered"], "level": "INFO", "propagate": False},
        "daphne.http": {"handlers": ["console_filtered"], "level": "INFO", "propagate": False},
    },
}

SITE_URL = env("SITE_URL", default="http://localhost:8000")


if __name__ == "__main__":


    print(f"DEBUG: {DEBUG}")


    print(f"BASE_DIR: {BASE_DIR}")


    print(f"STATIC_URL: {STATIC_URL}")


    print(f"STATIC_ROOT: {STATIC_ROOT}")
