"""
Django settings for _main project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import secrets
from pathlib import Path
import ssl

import dj_database_url
import semver

from django.utils.translation import gettext_lazy as _
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'), override=True)

# Log the loaded Redis URL (masked) for debugging
redis_url = os.environ.get('REDIS_URL', 'Not Set')
if redis_url.startswith('rediss://'):
    masked_url = redis_url.replace(redis_url.split('@')[0], 'rediss://***')
    print(f"Loading settings with REDIS_URL: {masked_url}")
else:
    print(f"Loading settings with REDIS_URL: {redis_url}")

# Before using your app in production, make sure to review Django's deployment checklist:
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Django requires a unique secret key for each Django app, that is used by several of its
# security features. To simplify initial setup (without hardcoding the secret in the source
# code) we set this to a random value every time the app starts. However, this will mean many
# Django features break whenever an app restarts (for example, sessions will be logged out).
# In your production apps you should set the `DJANGO_SECRET_KEY` config var explicitly.
# Make sure to use a long unique value, like you would for a password. See:
# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-SECRET_KEY
# SECURITY WARNING: keep the secret key used in production secret!

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

SECRET_KEY = env('SECRET_KEY')

IS_FLY_APP = env.str("FLY_APP", default="")
IS_PRODUCTION = bool(IS_FLY_APP)

CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[
    "https://krispc.fr",
    "https://www.krispc.fr",
    "https://pdf2cal.fly.dev"
])

MAPBOX_TOKEN = env('MAPBOX_TOKEN')
GOOGLE_MAPS_API_KEY = env('GOOGLE_MAPS_API_KEY')



DEBUG = False
# SECURITY WARNING: don't run with debug turned on in production!
if not IS_PRODUCTION:
    DEBUG = True

if not IS_PRODUCTION:
    SENDGRID_API_KEY = env('SENDGRID_API_KEY')
else:
    SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")

# On fly.io, it's safe to use a wildcard for `ALLOWED_HOSTS`, since the proxy performs
# validation of the Host header in the incoming HTTP request. On other platforms you may need
# to list the expected hostnames explicitly to prevent HTTP Host header attacks. See:
# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-ALLOWED_HOSTS
if IS_PRODUCTION:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = []

# CORS Configuration for API
# Allow API access from specific origins
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "https://krispc.fr",
    "https://www.krispc.fr",
    "http://localhost:3000",
    "http://localhost:5173",
])

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'accept-language',
]



# Application definition

INSTALLED_APPS = [
    # Use WhiteNoise's runserver implementation instead of the Django default, for dev-prod parity.
    "whitenoise.runserver_nostatic",
    # Uncomment this and the entry in `urls.py` if you wish to use the Django admin feature:
    # https://docs.djangoproject.com/en/4.2/ref/contrib/admin/
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Vite integration for modern frontend
    "django_vite",
    # "django_user_agents",
    "django_htmx",
    "crispy_forms",
    "crispy_bootstrap5",
    "channels",
    "hello",
    "chat",
    "addthem",
    "krispc",
    "wat",
    # pdf2cal apps
    "celery_progress",
    "p2c",
    "hub",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "plexus.apps.PlexusConfig",
]

ASGI_APPLICATION = '_main.asgi.application'
WSGI_APPLICATION = '_main.wsgi.application'

# Django Vite configuration for modern frontend assets
DJANGO_VITE = {
    'default': {
        'dev_mode': False,  # Set to False to use production build
        'dev_server_host': 'localhost',
        'dev_server_port': 5173,
        'manifest_path': BASE_DIR / 'krispc' / 'static' / 'dist' / '.vite' / 'manifest.json',
    }
}

REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'  # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True


if DEBUG:
    # Use in-memory channel layer for development
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    # Use Redis for production
    # Note: Redis Cloud with mTLS (client certificates) is not supported by channels_redis
    # out of the box. The rediss:// URL scheme provides SSL, but if client certs are required,
    # you may need to switch to a simpler Redis configuration or use a Redis without mTLS.
    # For now, we'll try connecting without SSL context to trigger a clearer error.
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Django doesn't support serving static assets in a production-ready way, so we use the
    # excellent WhiteNoise package to do so instead. The WhiteNoise middleware must be listed
    # after Django's `SecurityMiddleware` so that security redirects are still performed.
    # See: https://whitenoise.readthedocs.io
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "hub.middleware.EnsureDefaultLanguageMiddleware",  # Set default language before LocaleMiddleware
    "django.middleware.locale.LocaleMiddleware",  # Required for i18n URL patterns
    "krispc.middleware.APILanguageMiddleware",  # API-specific language detection
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "krispc.middleware.APIRequestLoggingMiddleware",  # API request logging
    # "django_user_agents.middleware.UserAgentMiddleware",
]

ROOT_URLCONF = "_main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "addthem/templates", "chat/templates", "_krispc/templates"),
            BASE_DIR / "p2c" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "p2c.context_processors.unread_updates_context",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Uses SQLite by default. Can be overridden with DATABASE_URL environment variable.
# https://github.com/jazzband/dj-database-url

if IS_FLY_APP:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "/data/db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "fr"
# LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"

# Media files (uploaded by users)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "media/"

# Additional locations for static files
STATICFILES_DIRS = [
    BASE_DIR / "krispc" / "static" / "dist",  # Vite build output
    BASE_DIR / "krispc" / "static",           # Images and other static assets
    BASE_DIR / "p2c" / "static",              # P2C static files
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "krispc/locale"),
    os.path.join(BASE_DIR, "locale"),
]


LANGUAGES = [
    ("fr", _("French")),
    ("en", _("English")),
]


STORAGES = {
    # Default file storage for uploaded files
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Enable WhiteNoise's GZip and Brotli compression of static assets:
    # https://whitenoise.readthedocs.io/en/latest/django.html#add-compression-and-caching-support
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Don't store the original (un-hashed filename) version of static files, to reduce slug size:
# https://whitenoise.readthedocs.io/en/latest/django.html#WHITENOISE_KEEP_ONLY_HASHED_FILES
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

WHITENOISE_MANIFEST_STRICT = False

# Configure caching - use in-memory cache for all environments
# Note: Redis Cloud requires mTLS (client certificates) which django_redis doesn't support well.
# Celery uses redis-py directly which does support mTLS.
# For caching, we use in-memory cache which is sufficient for single-instance deployments.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

VER = semver.VersionInfo.parse("2.3.0")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- P2C / PDF2Cal Specific Settings ---

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Connection timeout settings to prevent hanging when Redis is unavailable
CELERY_BROKER_CONNECTION_TIMEOUT = 10  # 10 seconds timeout for broker connection
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 3
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 10,
    'socket_connect_timeout': 10,
}

REDIS_CA_CERT_PATH = os.path.join(BASE_DIR, 'redis_remote_cert', 'redis_ca.pem')
REDIS_CLIENT_CERT_PATH = os.path.join(BASE_DIR, 'redis_remote_cert', 'redis-db-12916440-client-certificate', 'redis-db-12916440.crt')
REDIS_CLIENT_KEY_PATH = os.path.join(BASE_DIR, 'redis_remote_cert', 'redis-db-12916440-client-certificate', 'redis-db-12916440.key')

if REDIS_URL and REDIS_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_REQUIRED,
        'ssl_ca_certs': REDIS_CA_CERT_PATH,
        'ssl_certfile': REDIS_CLIENT_CERT_PATH,
        'ssl_keyfile': REDIS_CLIENT_KEY_PATH,
    }
    CELERY_REDIS_BACKEND_USE_SSL = CELERY_BROKER_USE_SSL

# Google OAuth2 Settings
GOOGLE_OAUTH2_CLIENT_ID = env("GOOGLE_OAUTH2_CLIENT_ID", default=None)
GOOGLE_OAUTH2_CLIENT_SECRET = env("GOOGLE_OAUTH2_CLIENT_SECRET", default=None)
GOOGLE_OAUTH2_REDIRECT_URI = env("GOOGLE_OAUTH2_REDIRECT_URI", default="http://localhost:8000/google/callback")
GOOGLE_OAUTH2_SCOPES = [
    "openid",
    "email",
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/calendar.readonly",
]

REST_FRAMEWORK = {
    # Renderers
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # For development
    ],
    
    # Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    
    # Permissions - Allow per-view control (views explicitly set their permissions)
    "DEFAULT_PERMISSION_CLASSES": [],
    
    # User settings
    "UNAUTHENTICATED_USER": None,
    
    # Schema generation
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    # Throttling
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",           # Anonymous users: 100 requests per hour
        "user": "1000/hour",          # Authenticated users: 1000 requests per hour
        "contacts": "5/minute",       # Contact form: 5 per minute
        "read_only": "60/minute",     # Read-only endpoints: 60 per minute
    },
    
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    
    # Filtering
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    
    # Versioning
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    "VERSION_PARAM": "version",
    
    # Exception handling
    "EXCEPTION_HANDLER": "krispc.exceptions.custom_exception_handler",
    
    # Datetime format
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'KrisPC & Plexus API',
    'DESCRIPTION': 'API for KrisPC IT services and Plexus SecondBrain.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# AI Configuration (Plexus)
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-pro-latest")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "p2c": {"handlers": ["console"], "level": "DEBUG", "propagate": True},
    },
}

SITE_URL = env("SITE_URL", default="http://localhost:8000")


if __name__ == "__main__":


    print(f"DEBUG: {DEBUG}")


    print(f"BASE_DIR: {BASE_DIR}")


    print(f"STATIC_URL: {STATIC_URL}")


    print(f"STATIC_ROOT: {STATIC_ROOT}")


    print(f"SENDGRID_API_KEY: {SENDGRID_API_KEY}")

