# Generated by Django 5.0.2 on 2026-01-18 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "Web"), ("mobile", "Mobile"), ("api", "API")],
                        default="web",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_ai_provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                        ],
                        default="gemini",
                        max_length=50,
                    ),
                ),
                (
                    "active_redis_env",
                    models.CharField(
                        choices=[("local", "Local Redis"), ("cloud", "Cloud Redis")],
                        default="local",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
        migrations.CreateModel(
            name="Thought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ideation", "Ideation"),
                            ("reference", "Reference"),
                            ("task", "Task"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        help_text="The AI model used for processing",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thoughts",
                        to="plexus.input",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thought",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="plexus.thought",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "thought",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="plexus.thought",
                    ),
                ),
            ],
        ),
    ]
