# Generated by Django 5.0.2 on 2026-01-19 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plexus", "0003_thoughtlink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"verbose_name": "Action", "verbose_name_plural": "Actions"},
        ),
        migrations.AlterModelOptions(
            name="input",
            options={"verbose_name": "Input", "verbose_name_plural": "Inputs"},
        ),
        migrations.AlterModelOptions(
            name="reviewqueue",
            options={
                "verbose_name": "Review Queue Item",
                "verbose_name_plural": "Review Queue Items",
            },
        ),
        migrations.AlterModelOptions(
            name="systemconfiguration",
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="thought",
            options={"verbose_name": "Thought", "verbose_name_plural": "Thoughts"},
        ),
        migrations.AlterModelOptions(
            name="thoughtlink",
            options={
                "verbose_name": "Thought Link",
                "verbose_name_plural": "Thought Links",
            },
        ),
        migrations.AddField(
            model_name="input",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="plexus/inputs/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="action",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("done", "Done"),
                    ("dismissed", "Dismissed"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="thought",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plexus.thought",
                verbose_name="Thought",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="input",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="input",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="input",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Processed"),
        ),
        migrations.AlterField(
            model_name="input",
            name="source",
            field=models.CharField(
                choices=[("web", "Web"), ("mobile", "Mobile"), ("api", "API")],
                default="web",
                max_length=50,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="reviewqueue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="reviewqueue",
            name="reason",
            field=models.TextField(verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="reviewqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="reviewqueue",
            name="thought",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="plexus.thought",
                verbose_name="Thought",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_ai_provider",
            field=models.CharField(
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                ],
                default="gemini",
                max_length=50,
                verbose_name="Active AI Provider",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="active_redis_env",
            field=models.CharField(
                choices=[("local", "Local Redis"), ("cloud", "Cloud Redis")],
                default="local",
                max_length=50,
                verbose_name="Active Redis Env",
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="ai_model",
            field=models.CharField(
                blank=True,
                help_text="The AI model used for processing",
                max_length=100,
                null=True,
                verbose_name="AI Model",
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="confidence_score",
            field=models.FloatField(verbose_name="Confidence Score"),
        ),
        migrations.AlterField(
            model_name="thought",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="thought",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="thought",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="input",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thoughts",
                to="plexus.input",
                verbose_name="Input",
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="type",
            field=models.CharField(
                choices=[
                    ("ideation", "Ideation"),
                    ("reference", "Reference"),
                    ("task", "Task"),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="thoughtlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="thoughtlink",
            name="reason",
            field=models.TextField(
                help_text="Why these thoughts are connected",
                verbose_name="Connection Reason",
            ),
        ),
        migrations.AlterField(
            model_name="thoughtlink",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_links",
                to="plexus.thought",
                verbose_name="Source Thought",
            ),
        ),
        migrations.AlterField(
            model_name="thoughtlink",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_links",
                to="plexus.thought",
                verbose_name="Target Thought",
            ),
        ),
    ]
