# Generated by Django 5.0.2 on 2026-01-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plexus", "0004_alter_action_options_alter_input_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
    ]
