# Generated by Django 5.0.2 on 2026-01-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plexus", "0005_alter_input_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, verbose_name="User ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("sequence", models.JSONField(verbose_name="Sequence")),
                (
                    "palette_id",
                    models.CharField(max_length=50, verbose_name="Palette ID"),
                ),
                ("size", models.IntegerField(verbose_name="Size")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Is Public"),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(default=False, verbose_name="Is AI Generated"),
                ),
                (
                    "generation_prompt",
                    models.TextField(
                        blank=True, null=True, verbose_name="Generation Prompt"
                    ),
                ),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="Tags")),
                (
                    "difficulty_rating",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Difficulty Rating"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="Like Count"),
                ),
                (
                    "complexity_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Complexity Score"
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Estimated Time (min)"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
                (
                    "parent_pattern_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Parent Pattern ID",
                    ),
                ),
                (
                    "search_vector",
                    models.TextField(
                        blank=True, null=True, verbose_name="Search Vector"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Deleted by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern",
                "verbose_name_plural": "Patterns",
                "db_table": "patterns",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("reminder", "Reminder"), ("system", "System")],
                        default="reminder",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="plexus.action",
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("remind_at", models.DateTimeField(verbose_name="Remind at")),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is sent")),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="plexus.action",
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["-remind_at"],
            },
        ),
    ]
