# Generated by Django 5.0.2 on 2026-01-31 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plexus", "0006_add_reminders_and_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plexus_inputs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
