# Generated by Django 5.0.2 on 2026-02-24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sasaccesslog",
            name="email_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sasaccesslog",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sasaccesslog",
            name="ipinfo_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sasaccesslog",
            name="turnstile_action",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sasaccesslog",
            name="turnstile_error_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sasaccesslog",
            name="turnstile_hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sasaccesslog",
            name="turnstile_success",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sasfile",
            name="download_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
